name: Polygon詠唱チェッカー

on:
  push:
    paths:
      - polygon_gui.py
  workflow_dispatch:

jobs:
  run-polygon-check:
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v3

      - name: Pythonセットアップ
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 詠唱GUIのコード検査
        run: python polygon_gui.py
